name: Continuous Integration Master

on:
  push:
    branches:
      - master
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytests
        run: |
          make tests